---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-creds
  namespace: pg-system
spec:
  encryptedData:
    password: AgBbNnr2c4jc6sgB3E8ryc4uEZEpAUGkaauDu0A95px2POxymRfwdnvSRAs7+QIeJsDNb+EW9wiYElIaxAnuktTFItwjkbTTBY8ZvjFVOx0XB7o69Vgn0GJ8wUDW/1zgHgNz1aqbwDU7TQZXI6dF1XXe4KZvJrDDzfUT4mmyi2akWCRiJ0jJIS0msG5B7twhz3/8i6niFmYe5toSWYknZKTrEzpJFAKeng08lu+qLRncJRCFkfQ2OLMk/H2WcsIfFHC4QrXB9EfpHO/7gN58TLCGbQjSUK025WwBv4Voj0cim5mkPIidOJjLSSgRCb+VOg23/fKi+i0mfq/YnzVAuoVU4b8siG74doBL8i/Vd3UqGgu9nmbL9cQOl0mB6egLTj+evH6/50GLI9ZpTS/7jcdtoBisVsLUAas/G8UVbqNpcQE3NgoL4KS66tP4dvOUwCN+pg/14Ny9BY4tCfgWooWd2JX82GR4BMWrqki2T+ip7LGBnPfCy1UFs5ph+WsdRo4h1bkjdrG6A4QnEAMf8Pz1YKCgD506yRPz675LYUEPe9mmIZQLOwn4Dzj86hXZR+lRO6TGqW4lT8dG1O1Pis9O/VE9FvBHWhDOxdocAAGUwWYIwAnKmy8EgLrviakeUjSqEIaT6JDQI/qJDdM0AhnkGUuyT3dXMLJhp1ZR6koMwNIqkplTxCOyG1isX69egNQh4ppH+byivv6qJQ==
    username: AgBUad2pdKFawQRxLbonY6hOeAe2ak5uv+2kNZuSOvDB5Alt6bMxTFcVcV8KuUAFC/7KWTEZakcjShUPVAWyxnrz20mt2Amu21ry3cyEVUFp4OhYVcNJCCgCwCHPAzlBWLhiyk3EMKZgZaGoKiQHjb3FBzZ0sRrSsUE+IjEu0rBR6IvFhH2v2+z28Ue18RMOf6o0bIOLyLrBqqEwkP/CESGZwRt0OC00PDZZ6hWmVTgrarwXRWtej+7A2mQGGtBEW2wvHpYtZBOkMU5oxrEsWB1AiHAc8N4nXx+y3zbXg8A83KwXuxjwEv4nyUgWFs6BCnwG1nEGBHK2I14zdwqJmfiWElJhxFU2eKhAo6bF4YrrvDzQCA8MeLcvmOnm8QFoGKETMOMLyJzPC8a7c1N97jbseBOPkSgjSfviT+1SECU8ezwWrbRhLbADxYEkrApNDXIRdhkRAuc66VBKLBY5XPS1xhMZBOZFf0k70B0l5CU/mKt5lAfnTOxYpwoL6f65KSZHKTpuaBuBIjuCYKL2HlRLukoj5RV1xMgph9mfhKdd3Mw9RDDvelXGYLk67qWZS6F3VNMbtd5uCEq98VE8nqy6kD/x5eGKdwGrQ/1lG8u/gEhRl632gIDRMl/baL+cuYqJozKgY+Rm2vk0dpT4lLXzWORU2TEL0QRJKosrjI/W4ARvlmSnFPgCHDpEftf5f3rzZSYqe95kl0PK6W3F
  template:
    metadata:
      name: database-creds
      namespace: pg-system
