apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- sealed-secrets-helm.yaml
- traefik-service.yaml
- traefik-ingress-route.yaml
- traefik-helm-chart-configuration.yaml
