apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  interval: 1h
  values: 
    prometheus:
      prometheusSpec:
        storage:
          volumeClaimTemplate:
            spec:
              selector:
                storage: prometheus
    alertmanager:
      alertmanagerSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              selector:
                storage: alertmanager
    grafana:
      persistence:
        enabled: true
        type: pvc
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        size: 5Gi
